/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.hackerday.client.tool.dashboard;

import java.awt.*;
import javax.swing.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import static com.okmich.hackerday.client.tool.dashboard.Handler.*;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Map;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

/**
 *
 * @author m.enudi
 */
public class ClientDashboardFrame extends javax.swing.JFrame {

    public ReportItemPanel panelContext;

    /**
     * Creates new form ClientDashboard
     *
     * @param itemPanelMap
     */
    public ClientDashboardFrame(Map<String, ReportItemPanel> itemPanelMap) {

        initComponents();

        getContentPane().add(itemPanelMap.get(TRAJ_DISTANCE_KEY));
        getContentPane().add(itemPanelMap.get(TRAJ_DURATION_KEY));
        getContentPane().add(itemPanelMap.get(USER_PERIOD_KEY));
        getContentPane().add(itemPanelMap.get(USER_TRAJ_KEY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - denis igoshev
    private void initComponents() {
      jMenuBar1 = new JMenuBar();
      jMenu1 = new JMenu();

      //======== this ========
      setTitle("Geolife Trajectories Dashboard");
      setMinimumSize(new Dimension(800, 600));
      Container contentPane = getContentPane();
      contentPane.setLayout(new GridLayout(2, 2, 10, 10));

      //======== jMenuBar1 ========
      {

        //======== jMenu1 ========
        {
          jMenu1.setText("View Details");
          jMenu1.setEnabled(false);
        }
        jMenuBar1.add(jMenu1);
      }
      setJMenuBar(jMenuBar1);
      pack();
      setLocationRelativeTo(null);

      //---- bindings ----
      bindingGroup = new BindingGroup();
      bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
        jMenu1, ELProperty.create("${}"),
        this, BeanProperty.create("defaultCloseOperation")));
      bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - denis igoshev
    private JMenuBar jMenuBar1;
    private JMenu jMenu1;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @param panelContext the panelContext to set
     */
    void setPanelContext(ReportItemPanel reportItemPanel) {
        if (this.panelContext == null || !this.panelContext.equals(reportItemPanel)) {
            if (this.panelContext != null) {
                this.panelContext.onMouseExit();
            }
            this.panelContext = reportItemPanel;
            jMenu1.setEnabled(true);
        } else {
            this.panelContext.onMouseExit();
            this.panelContext = null;
            jMenu1.setEnabled(false);
        }
    }
}
